/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Получить список всех бронирований (всех типов событий) */
        get: operations["Admin_listBookings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/bookings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Получить детали бронирования */
        get: operations["Admin_getBooking"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/bookings/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Отменить бронирование */
        post: operations["Admin_cancelBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/bookings/{id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Восстановить бронирование */
        post: operations["Admin_restoreBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Получить список всех типов событий владельца */
        get: operations["Admin_listEventTypes"];
        put?: never;
        /** @description Создать новый тип события */
        post: operations["Admin_createEventType"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/event-types/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Получить тип события по id */
        get: operations["Admin_getEventType"];
        /** @description Обновить тип события */
        put: operations["Admin_updateEventType"];
        post?: never;
        /** @description Удалить тип события */
        delete: operations["Admin_deleteEventType"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/owner": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Получить информацию о владельце (по умолчанию единственный) */
        get: operations["Admin_getOwner"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Создать бронирование (гостевой поток) */
        post: operations["Public_createPublicBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/bookings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Получить детали бронирования (для гостя, например, по ссылке из email) */
        get: operations["Public_getPublicBooking"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Получить список всех типов событий (для публичного просмотра) */
        get: operations["Public_listPublicEventTypes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/event-types/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Получить детали публичного типа события */
        get: operations["Public_getPublicEventType"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/event-types/{id}/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Получить доступные слоты для конкретного типа события */
        get: operations["Public_listAvailableSlots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/owner": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Получить информацию о владельце (для публичного просмотра) */
        get: operations["Public_getPublicOwner"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/slots/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Получить слот по id */
        get: operations["Public_getSlot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Бронирование — запись гостя на конкретный слот.
         *     Гость не создает аккаунт, указывает только контактные данные.
         * @example {
         *       "id": "00000000-0000-0000-0000-000000000004",
         *       "slotId": "00000000-0000-0000-0000-000000000010",
         *       "guestName": "Иван Петров",
         *       "guestEmail": "ivan@example.com",
         *       "notes": "Хочу обсудить проект",
         *       "status": "confirmed",
         *       "createdAt": "2026-06-10T12:00:00Z"
         *     }
         */
        Booking: {
            /** Format: uuid */
            id: string;
            /**
             * Format: uuid
             * @description Ссылка на слот
             */
            slotId: string;
            /** @description Имя гостя */
            guestName: string;
            /**
             * Format: email
             * @description Email гостя для уведомлений
             */
            guestEmail: string;
            /** @description Дополнительные заметки/вопросы */
            notes?: string;
            /** @description Статус бронирования */
            status: components["schemas"]["BookingStatus"];
            /**
             * Format: date-time
             * @description Время создания бронирования
             */
            createdAt: string;
        };
        /**
         * @description Статус бронирования
         * @enum {string}
         */
        BookingStatus: "confirmed" | "cancelled";
        ConflictError: {
            /** @enum {string} */
            code: "CONFLICT";
            message: string;
        };
        /**
         * @description Тело запроса для создания бронирования
         * @example {
         *       "slotId": "00000000-0000-0000-0000-000000000012",
         *       "guestName": "Иван Петров",
         *       "guestEmail": "ivan@example.com",
         *       "notes": "Хочу обсудить проект"
         *     }
         */
        CreateBookingRequest: {
            /** Format: uuid */
            slotId: string;
            guestName: string;
            guestEmail: string;
            notes?: string;
        };
        /**
         * @description Тело запроса для создания типа события
         * @example {
         *       "name": "Встреча 1 час",
         *       "description": "Командная встреча",
         *       "durationMinutes": 60
         *     }
         */
        CreateEventTypeRequest: {
            name: string;
            description?: string;
            /** Format: int32 */
            durationMinutes: number;
        };
        /**
         * @description Тип события — шаблон встречи, который создает владелец.
         *     Определяет название, описание и длительность.
         * @example {
         *       "id": "00000000-0000-0000-0000-000000000002",
         *       "ownerId": "00000000-0000-0000-0000-000000000001",
         *       "name": "Консультация 30 мин",
         *       "description": "Индивидуальная консультация",
         *       "durationMinutes": 30
         *     }
         */
        EventType: {
            /** Format: uuid */
            id: string;
            /**
             * Format: uuid
             * @description Ссылка на владельца
             */
            ownerId: string;
            /** @description Название типа события (например, "Консультация 30 мин") */
            name: string;
            /** @description Описание, отображается публично */
            description?: string;
            /**
             * Format: int32
             * @description Длительность встречи в минутах
             */
            durationMinutes: number;
        };
        /** @description Параметры запроса для фильтрации бронирований */
        ListBookingsQuery: {
            /**
             * Format: uuid
             * @description Фильтр по типу события
             */
            eventTypeId?: string;
            /** @description Фильтр по статусу */
            status?: components["schemas"]["BookingStatus"];
        };
        /** @description Параметры запроса для фильтрации слотов */
        ListSlotsQuery: {
            /**
             * Format: date-time
             * @description Дата начала периода (включительно) в формате ISO 8601
             */
            from?: string;
            /**
             * Format: date-time
             * @description Дата окончания периода (включительно) в формате ISO 8601
             */
            to?: string;
        };
        NotFoundError: {
            /** @enum {string} */
            code: "NOT_FOUND";
            message: string;
        };
        /**
         * @description Владелец календаря — один заранее заданный профиль.
         *     Используется в админской части по умолчанию.
         * @example {
         *       "id": "00000000-0000-0000-0000-000000000001",
         *       "name": "Анна Смирнова",
         *       "email": "anna@example.com",
         *       "timezone": "Europe/Moscow",
         *       "avatar": "https://i.pravatar.cc/150?u=anna"
         *     }
         */
        Owner: {
            /** Format: uuid */
            id: string;
            /** @description Имя владельца, отображается публично */
            name: string;
            /**
             * Format: email
             * @description Email для уведомлений
             */
            email: string;
            /** @description Часовой пояс для расчета слотов (например, Europe/Moscow) */
            timezone: string;
            /** @description URL аватара владельца */
            avatar: string;
        };
        /**
         * @description Слот — конкретный временной интервал для бронирования.
         *     Генерируется на основе типа события и доступности владельца.
         * @example {
         *       "id": "00000000-0000-0000-0000-000000000010",
         *       "eventTypeId": "00000000-0000-0000-0000-000000000002",
         *       "startTime": "2026-06-15T09:00:00Z",
         *       "endTime": "2026-06-15T09:30:00Z",
         *       "isAvailable": true
         *     }
         */
        Slot: {
            /** Format: uuid */
            id: string;
            /**
             * Format: uuid
             * @description Ссылка на тип события
             */
            eventTypeId: string;
            /**
             * Format: date-time
             * @description Начало слота в UTC
             */
            startTime: string;
            /**
             * Format: date-time
             * @description Окончание слота в UTC
             */
            endTime: string;
            /** @description Доступен ли слот для бронирования */
            isAvailable: boolean;
        };
        /**
         * @description Тело запроса для обновления типа события
         * @example {
         *       "name": "Обновленная консультация",
         *       "description": "Индивидуальная консультация (обновлено)",
         *       "durationMinutes": 45
         *     }
         */
        UpdateEventTypeRequest: {
            name?: string;
            description?: string;
            /** Format: int32 */
            durationMinutes?: number;
        };
        ValidationError: {
            /** @enum {string} */
            code: "VALIDATION_ERROR";
            message: string;
            details?: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    Admin_listBookings: {
        parameters: {
            query?: {
                eventTypeId?: string;
                status?: components["schemas"]["BookingStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example [
                     *       {
                     *         "id": "00000000-0000-0000-0000-000000000004",
                     *         "slotId": "00000000-0000-0000-0000-000000000010",
                     *         "guestName": "Иван Петров",
                     *         "guestEmail": "ivan@example.com",
                     *         "notes": "Хочу обсудить проект",
                     *         "status": "confirmed",
                     *         "createdAt": "2026-06-10T12:00:00Z"
                     *       },
                     *       {
                     *         "id": "00000000-0000-0000-0000-000000000006",
                     *         "slotId": "00000000-0000-0000-0000-000000000011",
                     *         "guestName": "Мария Козлова",
                     *         "guestEmail": "maria@example.com",
                     *         "notes": "Отменено по причине...",
                     *         "status": "cancelled",
                     *         "createdAt": "2026-06-11T14:30:00Z"
                     *       }
                     *     ]
                     */
                    "application/json": components["schemas"]["Booking"][];
                };
            };
        };
    };
    Admin_getBooking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    Admin_cancelBooking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    Admin_restoreBooking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
            /** @description The request conflicts with the current state of the server. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConflictError"];
                };
            };
        };
    };
    Admin_listEventTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example [
                     *       {
                     *         "id": "00000000-0000-0000-0000-000000000002",
                     *         "ownerId": "00000000-0000-0000-0000-000000000001",
                     *         "name": "Консультация 30 мин",
                     *         "description": "Индивидуальная консультация",
                     *         "durationMinutes": 30
                     *       },
                     *       {
                     *         "id": "00000000-0000-0000-0000-000000000005",
                     *         "ownerId": "00000000-0000-0000-0000-000000000001",
                     *         "name": "Встреча 1 час",
                     *         "description": "Командная встреча",
                     *         "durationMinutes": 60
                     *       }
                     *     ]
                     */
                    "application/json": components["schemas"]["EventType"][];
                };
            };
        };
    };
    Admin_createEventType: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "name": "Встреча 1 час",
                 *       "description": "Командная встреча",
                 *       "durationMinutes": 60
                 *     }
                 */
                "application/json": components["schemas"]["CreateEventTypeRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "00000000-0000-0000-0000-000000000007",
                     *       "ownerId": "00000000-0000-0000-0000-000000000001",
                     *       "name": "Встреча 1 час",
                     *       "description": "Командная встреча",
                     *       "durationMinutes": 60
                     *     }
                     */
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description Client error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    Admin_getEventType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "00000000-0000-0000-0000-000000000002",
                     *       "ownerId": "00000000-0000-0000-0000-000000000001",
                     *       "name": "Консультация 30 мин",
                     *       "description": "Индивидуальная консультация",
                     *       "durationMinutes": 30
                     *     }
                     */
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    Admin_updateEventType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "name": "Обновленная консультация",
                 *       "description": "Индивидуальная консультация (обновлено)",
                 *       "durationMinutes": 45
                 *     }
                 */
                "application/json": components["schemas"]["UpdateEventTypeRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "00000000-0000-0000-0000-000000000002",
                     *       "ownerId": "00000000-0000-0000-0000-000000000001",
                     *       "name": "Обновленная консультация",
                     *       "description": "Индивидуальная консультация (обновлено)",
                     *       "durationMinutes": 45
                     *     }
                     */
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
            /** @description Client error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    Admin_deleteEventType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    Admin_getOwner: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "00000000-0000-0000-0000-000000000001",
                     *       "name": "Анна Смирнова",
                     *       "email": "anna@example.com",
                     *       "timezone": "Europe/Moscow",
                     *       "avatar": "https://i.pravatar.cc/150?u=anna"
                     *     }
                     */
                    "application/json": components["schemas"]["Owner"];
                };
            };
        };
    };
    Public_createPublicBooking: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBookingRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            /** @description The request conflicts with the current state of the server. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConflictError"];
                };
            };
            /** @description Client error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    Public_getPublicBooking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    Public_listPublicEventTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example [
                     *       {
                     *         "id": "00000000-0000-0000-0000-000000000002",
                     *         "ownerId": "00000000-0000-0000-0000-000000000001",
                     *         "name": "Консультация 30 мин",
                     *         "description": "Индивидуальная консультация",
                     *         "durationMinutes": 30
                     *       },
                     *       {
                     *         "id": "00000000-0000-0000-0000-000000000005",
                     *         "ownerId": "00000000-0000-0000-0000-000000000001",
                     *         "name": "Встреча 1 час",
                     *         "description": "Командная встреча",
                     *         "durationMinutes": 60
                     *       }
                     *     ]
                     */
                    "application/json": components["schemas"]["EventType"][];
                };
            };
        };
    };
    Public_getPublicEventType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "00000000-0000-0000-0000-000000000002",
                     *       "ownerId": "00000000-0000-0000-0000-000000000001",
                     *       "name": "Консультация 30 мин",
                     *       "description": "Индивидуальная консультация",
                     *       "durationMinutes": 30
                     *     }
                     */
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    Public_listAvailableSlots: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example [
                     *       {
                     *         "id": "00000000-0000-0000-0000-000000000010",
                     *         "eventTypeId": "00000000-0000-0000-0000-000000000002",
                     *         "startTime": "2026-06-15T09:00:00Z",
                     *         "endTime": "2026-06-15T09:30:00Z",
                     *         "isAvailable": true
                     *       },
                     *       {
                     *         "id": "00000000-0000-0000-0000-000000000011",
                     *         "eventTypeId": "00000000-0000-0000-0000-000000000002",
                     *         "startTime": "2026-06-15T09:30:00Z",
                     *         "endTime": "2026-06-15T10:00:00Z",
                     *         "isAvailable": true
                     *       },
                     *       {
                     *         "id": "00000000-0000-0000-0000-000000000012",
                     *         "eventTypeId": "00000000-0000-0000-0000-000000000002",
                     *         "startTime": "2026-06-15T10:00:00Z",
                     *         "endTime": "2026-06-15T10:30:00Z",
                     *         "isAvailable": true
                     *       },
                     *       {
                     *         "id": "00000000-0000-0000-0000-000000000013",
                     *         "eventTypeId": "00000000-0000-0000-0000-000000000002",
                     *         "startTime": "2026-06-15T10:30:00Z",
                     *         "endTime": "2026-06-15T11:00:00Z",
                     *         "isAvailable": true
                     *       },
                     *       {
                     *         "id": "00000000-0000-0000-0000-000000000014",
                     *         "eventTypeId": "00000000-0000-0000-0000-000000000002",
                     *         "startTime": "2026-06-15T11:00:00Z",
                     *         "endTime": "2026-06-15T11:30:00Z",
                     *         "isAvailable": true
                     *       },
                     *       {
                     *         "id": "00000000-0000-0000-0000-000000000015",
                     *         "eventTypeId": "00000000-0000-0000-0000-000000000002",
                     *         "startTime": "2026-06-15T11:30:00Z",
                     *         "endTime": "2026-06-15T12:00:00Z",
                     *         "isAvailable": true
                     *       },
                     *       {
                     *         "id": "00000000-0000-0000-0000-000000000016",
                     *         "eventTypeId": "00000000-0000-0000-0000-000000000002",
                     *         "startTime": "2026-06-15T12:00:00Z",
                     *         "endTime": "2026-06-15T12:30:00Z",
                     *         "isAvailable": true
                     *       },
                     *       {
                     *         "id": "00000000-0000-0000-0000-000000000017",
                     *         "eventTypeId": "00000000-0000-0000-0000-000000000002",
                     *         "startTime": "2026-06-15T12:30:00Z",
                     *         "endTime": "2026-06-15T13:00:00Z",
                     *         "isAvailable": true
                     *       },
                     *       {
                     *         "id": "00000000-0000-0000-0000-000000000018",
                     *         "eventTypeId": "00000000-0000-0000-0000-000000000002",
                     *         "startTime": "2026-06-15T13:00:00Z",
                     *         "endTime": "2026-06-15T13:30:00Z",
                     *         "isAvailable": true
                     *       },
                     *       {
                     *         "id": "00000000-0000-0000-0000-000000000019",
                     *         "eventTypeId": "00000000-0000-0000-0000-000000000002",
                     *         "startTime": "2026-06-15T13:30:00Z",
                     *         "endTime": "2026-06-15T14:00:00Z",
                     *         "isAvailable": true
                     *       },
                     *       {
                     *         "id": "00000000-0000-0000-0000-00000000001a",
                     *         "eventTypeId": "00000000-0000-0000-0000-000000000002",
                     *         "startTime": "2026-06-15T14:00:00Z",
                     *         "endTime": "2026-06-15T14:30:00Z",
                     *         "isAvailable": true
                     *       },
                     *       {
                     *         "id": "00000000-0000-0000-0000-00000000001b",
                     *         "eventTypeId": "00000000-0000-0000-0000-000000000002",
                     *         "startTime": "2026-06-15T14:30:00Z",
                     *         "endTime": "2026-06-15T15:00:00Z",
                     *         "isAvailable": true
                     *       },
                     *       {
                     *         "id": "00000000-0000-0000-0000-00000000001c",
                     *         "eventTypeId": "00000000-0000-0000-0000-000000000002",
                     *         "startTime": "2026-06-15T15:00:00Z",
                     *         "endTime": "2026-06-15T15:30:00Z",
                     *         "isAvailable": true
                     *       },
                     *       {
                     *         "id": "00000000-0000-0000-0000-00000000001d",
                     *         "eventTypeId": "00000000-0000-0000-0000-000000000002",
                     *         "startTime": "2026-06-15T15:30:00Z",
                     *         "endTime": "2026-06-15T16:00:00Z",
                     *         "isAvailable": true
                     *       },
                     *       {
                     *         "id": "00000000-0000-0000-0000-00000000001e",
                     *         "eventTypeId": "00000000-0000-0000-0000-000000000002",
                     *         "startTime": "2026-06-15T16:00:00Z",
                     *         "endTime": "2026-06-15T16:30:00Z",
                     *         "isAvailable": true
                     *       },
                     *       {
                     *         "id": "00000000-0000-0000-0000-00000000001f",
                     *         "eventTypeId": "00000000-0000-0000-0000-000000000002",
                     *         "startTime": "2026-06-15T16:30:00Z",
                     *         "endTime": "2026-06-15T17:00:00Z",
                     *         "isAvailable": true
                     *       },
                     *       {
                     *         "id": "00000000-0000-0000-0000-000000000020",
                     *         "eventTypeId": "00000000-0000-0000-0000-000000000002",
                     *         "startTime": "2026-06-15T17:00:00Z",
                     *         "endTime": "2026-06-15T17:30:00Z",
                     *         "isAvailable": true
                     *       },
                     *       {
                     *         "id": "00000000-0000-0000-0000-000000000021",
                     *         "eventTypeId": "00000000-0000-0000-0000-000000000002",
                     *         "startTime": "2026-06-15T17:30:00Z",
                     *         "endTime": "2026-06-15T18:00:00Z",
                     *         "isAvailable": true
                     *       }
                     *     ]
                     */
                    "application/json": components["schemas"]["Slot"][];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    Public_getPublicOwner: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "00000000-0000-0000-0000-000000000001",
                     *       "name": "Анна Смирнова",
                     *       "email": "anna@example.com",
                     *       "timezone": "Europe/Moscow",
                     *       "avatar": "https://i.pravatar.cc/150?u=anna"
                     *     }
                     */
                    "application/json": components["schemas"]["Owner"];
                };
            };
        };
    };
    Public_getSlot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Slot"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
}
